### ISSUE TITLE
After build, first level does not transmit waves upon start

### ISSUE THREAD

**Issue by lmandres** [lmandres/GGJTeamPSU2018#1]
# Description
After build, first level does not transmit waves upon start

# Steps to Reproduce
1. Build Space Bubbles to executable
2. Double-click on executable
3. Select settings and click "Play!"
4. Click "New Game" button

# Expected functionality
The game should send a transmission that is stopped by the planet.

# Actual functionality
On all the levels, When you click the "Send Transmission" button, the game plays a sound like it is sending a transmission, but no radio waves are transmitted.

# Notes
The "Emitter" is stuck behind the game menu.  Perhaps the collider is being absorbed by the game menu.

**Comment by lmandres** [comment]
As of the master repository on 2018-01-28 15-03, this seems to be working for level 1 and level 2.

**Comment by Klezst** [comment]
Note that the issue was due to Unity not including the particle shader in the build. I had to add it under Edit -> Project Settings -> Graphics.
